version: '3'
services:
  db:
    image: mysql:5.7.22
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    restart: always

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: rootpass
    ports:
      - 443:443
      - 80:80
    restart: always
volumes:
  db_data:
